### ISSUE TITLE
Проверьте домашнее задание №5

### ISSUE THREAD

**Issue by Derzk1u** [MIEE-ACS/domashnee-zadanie-no5-Derzk1u#1]

**Comment by d-makarenko** [comment]
Есть замечание.
Метод проверки попадания точки внутрь окружности согласно заданию должен был быть реализован в виде метода класса Circle. Поскольку следующим этапом должна быть инкапсуляция свойств класса, то у MainWindow не останется возможности проверять это самостоятельно.
